### ISSUE TITLE
cant find config file 

### ISSUE THREAD

**Issue by soydepr** [spujadas/lighttpd-docker#13]
first , thanks for this image .

not able to find file /etc/lighttpd/lighttpd.conf  is it on local host.

also when i try to connect to the console using portainer it fails to connect

**Comment by spujadas** [comment]
> not able to find file /etc/lighttpd/lighttpd.conf is it on local host.

No, it's in the image (see https://github.com/spujadas/lighttpd-docker/tree/master/etc/lighttpd).
If you want to use your own, then you'll need to override the configuration in the container by bind-mount a file or directory on the host where the container is running (see https://github.com/spujadas/lighttpd-docker#usage and https://docs.docker.com/storage/bind-mounts/).

> also when i try to connect to the console using portainer it fails to connect

In Portainer, connect using `/bin/ash` instead of the default `/bin/bash`.

![image](https://user-images.githubusercontent.com/930566/76704690-0a9aa780-66db-11ea-8e4f-0a4e282e640a.png)
