### ISSUE TITLE
Effectively dead code in Dockerfile?

### ISSUE THREAD

**Issue by hartwork** [spujadas/lighttpd-docker#19]
Hi! It came to my attention that at …

https://github.com/spujadas/lighttpd-docker/blob/3cfc6cf5058b226199761fc9256d10e40337f584/Dockerfile#L12-L16

… file ` /etc/lighttpd/lighttpd.conf` is extended and then overritten by `COPY etc/lighttpd/* /etc/lighttpd/`. Unless I am missing soemthing, the `RUN` line can be dropped. True?

**Comment by spujadas** [comment]
Embarrassingly, this has been here for a very long time and I'd never noticed it before 😅 
You're absolutely right, the `RUN ...` line shouldn't be there, a) because it is indeed overwritten, and b) because the `server.network-backend = "writev"` is in `lighttpd.conf` anyway.
Will update the `Dockerfile`.
